### ISSUE TITLE
`catGroup` param sometimes not loading correctly

### ISSUE THREAD

**Issue by stdavis** [agrc/raster#131]
From @rkelson:
>When you get a chance can you revisit why links like these do not always open correctly? They seem to hang the first time you click the link but after a page reload they open rapidly and correctly at Step 2
https://raster.utah.gov/?catGroup=.5%20Meter%20%7B2020%20Northern%20Central%20Utah%20LiDAR%7D,1%20Meter%20%7B2020%20Northern%20Central%20Utah%20LiDAR%7D&title=Northern%20Central%20Utah%202020%20LiDAR

>I think it has to do with no one using that link or those types of links in a while and something has to 'wake up'. It's been doing this for years if you recall.

**Comment by stdavis** [comment]
I increased the min/max pooling to 2/8 respectively. We'll leave this open and see if you get any more complaints or see any other instances that fail to load completely.

**Comment by stdavis** [comment]
It sounds like this is still an issue. What should probably happen is that the sidebar needs to be disabled and a loading indicator displayed until the catGroup requests have completed.

**Comment by steveoh** [comment]
Do you think some data indexes would help?

**Comment by stdavis** [comment]
![image](https://github.com/agrc/raster/assets/1326248/b41f92ee-4d19-44ea-a858-1406c30b7a1b)

**Comment by stdavis** [comment]
@rkelson I've got this fix implemented and deployed to staging (https://raster.dev.utah.gov) in [version 2.4.0-0](https://github.com/agrc/raster/releases/tag/v2.4.0-0). Please give it a look and let me know what you think.

**Comment by rkelson** [comment]
This is looking like an improvement. The ?CatGroup URLs are loading immediately but the first time I tried a ?Cat= URL it took about 5 seconds to load. Below are 2 urls I've been trying:

https://raster.dev.utah.gov/?cat=.5%20Meter%20%7B2022%20Fish%20Springs%20LiDAR%7D&title=Fish%20Springs%202022%20Topo-Bathy%20LiDAR

https://raster.dev.utah.gov/?catGroup=.5%20Meter%20%7B2018%20Uintah%20Basin%20Heber%20Valley%20LiDAR%7D,1%20Meter%20%7B2018%20Uintah%20Basin%20Heber%20Valley%20LiDAR%7D&title=Uintah%20Basin%20and%20Heber%20Valley%202018%20LiDAR

**Comment by stdavis** [comment]
Yes, I didn't do anything to speed up the load times. I just added the loading indicator. I think that the load times are a function of sending a bunch of requests to the service at once. We can take a fresh look at that problem when we do the rewrite.

**Comment by stdavis** [comment]
@rkelson This has been pushed to production as part of the v2.4.0 release.
