### ISSUE TITLE
"..._x" does not exist

### ISSUE THREAD

**Issue by steveoh** [agrc/raster#15]
`"..\forklift-garage\SGID10 as INDICES.sde\LiDAR2011_10ft_DavisCo_DEM_Tile_x" does not exist`

```
INFO    09-20 23:49:02       lift:   49 crate: LiDAR2011_10ft_DavisCo_DEM_Tile_x
DEBUG   09-20 23:49:02       lift:   55 {   'destination': u'C:\\Scheduled\\staging\\raster.gdb\\LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'destination_name': u'LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'source': u'c:\\python27\\arcgis10.3\\lib\\site-packages\\forklift\\..\\forklift-garage\\SGID10 as INDICES.sde\\LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'source_name': u'LiDAR2011_10ft_DavisCo_DEM_Tile_x',
ERROR   09-20 23:49:18       core:   68 unhandled exception: "c:\python27\arcgis10.3\lib\site-packages\forklift\..\forklift-garage\SGID10 as INDICES.sde\LiDAR2011_10ft_DavisCo_DEM_Tile_x" does not exist for crate {   'destination': u'C:\\Scheduled\\staging\\raster.gdb\\LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'destination_name': u'LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'source': u'c:\\python27\\arcgis10.3\\lib\\site-packages\\forklift\\..\\forklift-garage\\SGID10 as INDICES.sde\\LiDAR2011_10ft_DavisCo_DEM_Tile_x',
    'source_name': u'LiDAR2011_10ft_DavisCo_DEM_Tile_x',
IOError: "c:\python27\arcgis10.3\lib\site-packages\forklift\..\forklift-garage\SGID10 as INDICES.sde\LiDAR2011_10ft_DavisCo_DEM_Tile_x" does not exist
INFO    09-20 23:49:18       lift:   61 result: ('Unhandled exception during update.', u'"c:\\python27\\arcgis10.3\\lib\\site-packages\\forklift\\..\\forklift-garage\\SGID10 as INDICES.sde\\LiDAR2011_10ft_DavisCo_DEM_Tile_x" does not exist')
```

I can only think that something got crossed up with [this bit of code](https://github.com/agrc/forklift/blob/fcdb6e1acc33be077b6c6d3838221c8e1a348371/src/forklift/core.py#L323-L328) which is supposed to act on the destination.

I don't think an elevated privilege user should be used here as it seems like we may have been creating temp data in the SGID. I think we should stick with a read only user.

## Update

The [arcpy.workspace.env](https://github.com/agrc/raster/blob/master/scripts/RasterPallet.py#L20) is being set to the staging gdb. That seems incorrect. Shouldn't it be the SGID to get the correct list? How would this run the first time if you don't stage the data yourself? 

Let's be explicit with the crate names. The list feature classes is neat and concise but problematic.

**Comment by stdavis** [comment]
The forklift code looks correct to me. I don't see it creating temp data in the source.

We need to use the INDICES user since a bunch of those datasets are not visible to the agrc user. I believe that they didn't want to clutter up the SGID with them.

I'll switch to explicit crate names. I thought that it would make adding new layers (which happens periodically) easier. I was going to just filter out names that ended with "_x" but I will go with the make-steve-happy solution which I've found to be the safer way in the past. :)
