### ISSUE TITLE
Add new "product" URL Parameter

### ISSUE THREAD

**Issue by stdavis** [agrc/raster#158]
From @rkelson 
>I am sure I asked this before and I understand the Raster app is a touchy subject, but is there anything that could be done so you could format a URL to start the app in Step 2 with one of the Step 1 products already checked such as Lidar DEMs? Cat and CatGroup URLs require specific project names and products, from the 'Category' field in the extents layer, but my idea would be a link that opened the app with Lidar DEMs already checked. Maybe something like ?product=. I am working with Steve on the new website is why I ask. I would basically be a link in the top card on the elevation and terrain page.

<img width="676" alt="image" src="https://github.com/agrc/raster/assets/1326248/3fb9fb8b-cf6c-433f-8548-1026f3e6b3f5">

**Comment by stdavis** [comment]
@rkelson I've got this implemented and deployed to staging (https://raster.dev.utah.gov) in [version 2.4.0-0](https://github.com/agrc/raster/releases/tag/v2.4.0-0). Please give it a look and let me know what you think.

I added docs for this feature to [the readme](https://github.com/agrc/raster/tree/dev?tab=readme-ov-file#optional-url-parameters). Note that I wasn't sure if you would want to be able to pass multiple products so I made the parameter name `products` (plural) and allow you to pass multiple comma-separated values.

**Comment by rkelson** [comment]
this is working perfectly. Thank you for anticipating multiple products and I really like that it uses an index instead of the product name.

**Comment by rkelson** [comment]
@stdavis you rock!
