### ISSUE TITLE
Survey app users for their input on changes/improvements

### ISSUE THREAD

**Issue by nathankota** [agrc/raster#169]
Pop-up/splash screen on the website  with a survey to help direct the next generation of the raster app with questions such as:
- Would they prefer data-first or project-first results? 
- Would they like a bulk downloader csv (and do they have a preference for one that they use at the moment?)
- Maybe a mock-up of sorts
- General feedback

**Comment by steveoh** [comment]
What about broad questions like, 

- What are you trying to accomplish when you come to this website. 
- Do you prefer this screen or that screen when viewing what is available in your area of interest. 
- What does this application do well now
- What could it do better

**Comment by nathankota** [comment]
Survey implemented by Rachel and team
