### ISSUE TITLE
WebMerc previews

### ISSUE THREAD

**Issue by rkelson** [agrc/raster#2]
alter the Preview button to use the Discover WebMerc services instead of the Rest_Endpoints on mapserv.

Should a new filed be added "DiscoverEnd" or something else or should we just keep using the REST_Endpoint field.

**Comment by stdavis** [comment]
I would proposed that we use a more generic field name such as "Endpoint". That way we can leave it open to put more than just discover urls in there.

**Comment by rkelson** [comment]
'Endpoint' has been added but not populated in Aerial_Photography_Extents but not the other "Extents" layers

**Comment by stdavis** [comment]
@rkelson: Is the data ready for me to start working on this?

**Comment by rkelson** [comment]
I'll get the field added and populated for the extents layers. I'll keep you updated on the progress

**Comment by rkelson** [comment]
is this the configuration of Endpoint you are looking for?

https://storage.googleapis.com/state-of-utah-naip-2006-nrg/{z}/{x}/{y}

**Comment by rkelson** [comment]
I've added 'ServiceName' str 25 to:
LOCAL...DRG_Extents
SGID10.LiDAR_Extents
SGID10.DEM_Extents
SGID10.Contour_Extents
SGID10.Aerial_Photography_Extents

<Null> is the value if there is no ServiceName

Since DRG_Extents and all the indices are local I have copied the edited data to K:\rkelson\willcall\DRGs.gdb for you to grab

as a result of the way the Topo base map service was created it has a ServiceName = "topo-tiles/Topo'

ServiceName has been populated for DRG_Extents and Aerial_Photography_Extents
