### ISSUE TITLE
Category Help Text

### ISSUE THREAD

**Issue by stdavis** [agrc/raster#27]
From @rkelson 
> It would be cool if each had an alt tag / title text (steve suggested the acronym tag) to explain what they are

**Comment by stdavis** [comment]
@rkelson I pushed a test for this functionality for the "Aerial Photography" category only to http://test.mapserv.utah.gov/raster. How does something like this ([abbr tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr)) look to you?

If you are happy, would you get me the text that you want for each category?

**Comment by rkelson** [comment]
I don't think I like the line under the category

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by stdavis** [comment]
What about something like the "?"s in https://enviro.deq.utah.gov?
![image](https://user-images.githubusercontent.com/1326248/37218919-19d26018-237f-11e8-99bb-3da32a2d10ea.png)

**Comment by rkelson** [comment]
Yes I think I like the "?" better that the underscores. Let's roll with them

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by stdavis** [comment]
Will do. Would you like provide the text for each category that you want?

**Comment by stdavis** [comment]
I just pushed the "?" option to http://test.mapserv.utah.gov/raster with placeholder text.

**Comment by rkelson** [comment]
•	Aerial Photography
Digital aerial photography
•	LiDAR DEMs
Digital elevation models derived from LiDAR
•	USGS DEMs
U.S. Geological Survey digital elevation models from The National Map
•	Auto-Correlated DEMs
Digital elevation models derived through an auto-correlation process from aerial photography
•	Contours
Contour lines derived at various intervals from Lidar and other sources
•	USGS Topo Maps
U.S. Geological Survey topographic maps
