### ISSUE TITLE
New Category: Historical Scanned Aerial Photography

### ISSUE THREAD

**Issue by stdavis** [agrc/raster#28]
From @rkelson 
> I changed my mind about adding the new scanned extents to the current Aerial Photography extents; it would return too many results. I propose making a new category named something like Historical Scanned Aerial Photography.

We are still waiting for the data for this, right?

**Comment by rkelson** [comment]
the UGS data is ready to be wired up into Raster but the new additions I
will be creating are weeks out, but in the same category.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by stdavis** [comment]
OK. I'd rather wait and do it all at once unless there's a pressing reason to get the UGS data in.

**Comment by rkelson** [comment]
I'm going to get the UGS tile index and extent setup as Historical Scanned Aerial Photography so we can start testing. The new scans I will add in the coming months will simply need a forklift for the extent addition and 2 new tile indices added to the .mxd

BTW - I don't see "futures"

**Comment by stdavis** [comment]
"Futures" is a heading your original description for #26 under which you put two items about the help text and the new category. No big deal.

**Comment by rkelson** [comment]
here is the description for Historical Scanned Aerial Photography when we are ready to add the category:

Historical scanned aerial photography that is not georeferenced

**Comment by rkelson** [comment]
There are 2 new layers in SDE for the new category _Historical Scanned Aerial Photography_
SGID10.INDICES.Scanned_Aerial_Photography_Extents
SGID10.INDICES.Scanned_Aerial_Photography

Let me know when this is ready to test

**Comment by stdavis** [comment]
@rkelson Did I let this slip through the cracks? Or are you still working on the data?

**Comment by rkelson** [comment]
I'm not sure but I will take a look at test raster and will let you know.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by stdavis** [comment]
OK. Closing this for now.
