### ISSUE TITLE
Remove 'ESRI' popup on logo

### ISSUE THREAD

**Issue by rkelson** [agrc/raster#29]
![esri](https://user-images.githubusercontent.com/6200941/38646247-63d67674-3da4-11e8-8f65-a1881ffb971c.png)

When you hover over the 'Fly Tiara' AGRC logo in the bottom right in the Raster apps is says "ESRI". Please remove any references to ESRI from the app.

It also is present in Atlas and PLSS but not Parcels

**Comment by steveoh** [comment]
:trollface:

**Comment by stdavis** [comment]
This is not an issue for the new react-based project (see https://atlas.utah.gov/ as an example). I'm going to punt this until the project gets rewritten...
