### ISSUE TITLE
Geocoding Is Broken

### ISSUE THREAD

**Issue by stdavis** [agrc/raster#34]
![image](https://user-images.githubusercontent.com/1326248/55128197-51f9e380-50d8-11e9-9077-83cb43e94b5f.png)

**Comment by rkelson** [comment]
Geocoding is still broken. If we can't keep it up and running let's remove the Find an Address functionality

**Comment by stdavis** [comment]
My apologies for letting this one slip through the cracks. I've got it fixed and am pushing a new build now.
