### ISSUE TITLE
Presentation error

### ISSUE THREAD

**Issue by rkelson** [agrc/raster#44]
in the Raster app there are records that have a "Flight Date Location" value of:
`'tile .XML file (<caldate>)' `
but they display in the More Info window as:
`'tile .XML file (&amp;lt;caldate&amp;gt;)'`

I could change `'(<caldate>)'` to `'(caldate tag)'` if there is not a better way to fix this issue

**Comment by steveoh** [comment]
What are the steps that would lead to the raster app showing this value?

**Comment by rkelson** [comment]
![image](https://user-images.githubusercontent.com/6200941/85629721-9e133b00-b62f-11ea-8f93-40e1a1f353c2.png)

**Comment by steveoh** [comment]
It appears that every time you click the `more info` the data is re-encoded. The first time it displays correctly, but each click fouls it up more. I suspect the bug is here

https://github.com/agrc/raster/blob/7e754267425926aeff417abe9956318710cf3172/_src/app/ProductResult.js#L412-L421
