### ISSUE TITLE
remove 'AGRC' from app

### ISSUE THREAD

**Issue by rkelson** [agrc/raster#52]
I guess it is time to change these to UGRC
![image](https://user-images.githubusercontent.com/6200941/123127776-d21e6900-d407-11eb-86c5-ceb5c0609532.png)

**Comment by steveoh** [comment]
We will do one big swoop when the time comes. It is good to identify items that should change but let's try to have a more organized approach to our name change.

**Comment by stdavis** [comment]
I'm assuming that since gis.utah.gov has been updated that I am good to act on this issue.
