### ISSUE TITLE
Add new tile indices

### ISSUE THREAD

**Issue by rkelson** [agrc/raster#53]
No rush so at your leisure please add the following tile indices from L:\agrc\raster\Lidar.gdb to the raster app .aprx. This should be the last of them for a while.

LiDAR2020_100cm_CentralSouthernUtah_DEM_Tiles
LiDAR2020_100cm_CentralSouthernUtah_DSM_Tiles
LiDAR2020_100cm_Z11_CentralSouthernUtah_DEM_Tiles
LiDAR2020_100cm_Z11_CentralSouthernUtah_DSM_Tiles
LiDAR2020_100cm_NorthernCentralUtah_DEM_Tiles
LiDAR2020_100cm_NorthernCentralUtah_DSM_Tiles
LiDAR2020_100cm_Z11_NorthernCentralUtah_DEM_Tiles
LiDAR2020_100cm_Z11_NorthernCentralUtah_DSM_Tiles
LiDAR2020_50cm_NorthernCentralUtah_DEM_Tiles
LiDAR2020_50cm_NorthernCentralUtah_DSM_Tiles
LiDAR2020_50cm_Z11_NorthernCentralUtah_DEM_Tiles
LiDAR2020_50cm_Z11_NorthernCentralUtah_DSM_Tiles

**Comment by stdavis** [comment]
This should be done.

**Comment by rkelson** [comment]
🌟

Rick Kelson
Utah Geospatial Resource Center (UGRC)
*Yes we've changed our name
<https://gis.utah.gov/agrc-name-change-to-utah-geospatial-resource-center-ugrc/>*
801.433.7891
gis.utah.gov
